"""removed id col to course offerings

Revision ID: 003e03f924a9
Revises: 6fcf52223f56
Create Date: 2025-12-31 22:21:28.716869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003e03f924a9'
down_revision = '6fcf52223f56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_offerings', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_offerings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.VARCHAR(length=64), nullable=False))

    # ### end Alembic commands ###
