"""added suggested courses col

Revision ID: 57bfacf491bd
Revises: d2df1423dca5
Create Date: 2025-12-30 00:00:57.840765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57bfacf491bd'
down_revision = 'd2df1423dca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unknown_course_suggestions', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_column('unknown_course_suggestions')

    # ### end Alembic commands ###
