"""Added priority column in req groups with default val

Revision ID: 6a61d15a3951
Revises: f6abe0d0bd86
Create Date: 2026-01-09 22:59:41.209605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a61d15a3951'
down_revision = 'f6abe0d0bd86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirement_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=False,server_default='0'))
        batch_op.create_index(batch_op.f('ix_requirement_groups_priority'), ['priority'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirement_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirement_groups_priority'))
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
