"""added id col to course offerings

Revision ID: 6fcf52223f56
Revises: 57bfacf491bd
Create Date: 2025-12-31 22:18:28.971833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fcf52223f56'
down_revision = '57bfacf491bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_offerings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_offerings', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
