"""Added new table

Revision ID: 90ee2225ecc2
Revises: 6a61d15a3951
Create Date: 2026-01-10 00:00:07.759288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90ee2225ecc2'
down_revision = '6a61d15a3951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_allocations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_profile_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=64), nullable=False),
    sa.Column('requirement_slot_id', sa.String(length=64), nullable=False),
    sa.Column('term', sa.String(length=120), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['requirement_slot_id'], ['requirement_slots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_profile_id', 'course_id', name='uq_allocation_student_course'),
    sa.UniqueConstraint('student_profile_id', 'requirement_slot_id', 'course_id', name='uq_allocation_student_slot')
    )
    with op.batch_alter_table('course_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_allocations_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_allocations_requirement_slot_id'), ['requirement_slot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_allocations_student_profile_id'), ['student_profile_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_allocations_student_profile_id'))
        batch_op.drop_index(batch_op.f('ix_course_allocations_requirement_slot_id'))
        batch_op.drop_index(batch_op.f('ix_course_allocations_course_id'))

    op.drop_table('course_allocations')
    # ### end Alembic commands ###
