"""added id col to course offerings

Revision ID: 95dd7869c924
Revises: 003e03f924a9
Create Date: 2025-12-31 22:26:18.393244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95dd7869c924'
down_revision = '003e03f924a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_offerings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.String(length=64), nullable=False))
        batch_op.alter_column('course_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('campus_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_offerings', schema=None) as batch_op:
        batch_op.alter_column('campus_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('course_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###
