"""add student profile

Revision ID: ccf90f525014
Revises: d05ee0bf31ad
Create Date: 2025-12-23 22:53:45.142929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccf90f525014'
down_revision = 'd05ee0bf31ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('campus_id', sa.String(length=64), nullable=True),
    sa.Column('major_id', sa.String(length=64), nullable=True),
    sa.Column('expected_grad_year', sa.Integer(), nullable=True),
    sa.Column('courses_by_term', sa.JSON(), nullable=False),
    sa.Column('unknown_courses', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_profiles_campus_id'), ['campus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_profiles_major_id'), ['major_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_profiles_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_student_profiles_major_id'))
        batch_op.drop_index(batch_op.f('ix_student_profiles_campus_id'))

    op.drop_table('student_profiles')
    # ### end Alembic commands ###
