"""Update schema!

Revision ID: d2df1423dca5
Revises: de3282e9d684
Create Date: 2025-12-28 23:20:27.374038

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'd2df1423dca5'
down_revision = 'de3282e9d684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prereq_rules', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('prereq_notes', sa.Text(), nullable=True))
        batch_op.drop_column('prereq_course_ids')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prereq_course_ids', sqlite.JSON(), nullable=False))
        batch_op.drop_column('prereq_notes')
        batch_op.drop_column('prereq_rules')

    # ### end Alembic commands ###
