"""added rest of models

Revision ID: de3282e9d684
Revises: ccf90f525014
Create Date: 2025-12-26 00:58:29.870619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de3282e9d684'
down_revision = 'ccf90f525014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campuses',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campuses_name'), ['name'], unique=False)

    op.create_table('departments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('campus_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campus_id', 'name', name='uq_department_campus_name')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_campus_id'), ['campus_id'], unique=False)

    op.create_table('courses',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.String(length=64), nullable=False),
    sa.Column('prereq_course_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_title'), ['title'], unique=False)

    op.create_table('majors',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('degree', sa.String(length=120), nullable=False),
    sa.Column('department_id', sa.String(length=64), nullable=False),
    sa.Column('campus_id', sa.String(length=64), nullable=False),
    sa.Column('total_credits_required', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campus_id', 'department_id', 'name', 'degree', name='uq_major_campus_dept_name_degree')
    )
    with op.batch_alter_table('majors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_majors_campus_id'), ['campus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_majors_department_id'), ['department_id'], unique=False)

    op.create_table('course_offerings',
    sa.Column('course_id', sa.String(length=64), nullable=False),
    sa.Column('campus_id', sa.String(length=64), nullable=False),
    sa.Column('terms_offered', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'campus_id')
    )
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.create_foreign_key("fk_student_profiles_campus_id__campuses", 'campuses', ['campus_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key("fk_student_profiles_major_id__majors", 'majors', ['major_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('course_offerings')
    with op.batch_alter_table('majors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_majors_department_id'))
        batch_op.drop_index(batch_op.f('ix_majors_campus_id'))

    op.drop_table('majors')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_title'))
        batch_op.drop_index(batch_op.f('ix_courses_department_id'))

    op.drop_table('courses')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_campus_id'))

    op.drop_table('departments')
    with op.batch_alter_table('campuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campuses_name'))

    op.drop_table('campuses')
    # ### end Alembic commands ###
