"""Ontology + Catalog models final (fixed)

Revision ID: e1cae9f885da
Revises: f2a8a10034be
Create Date: 2026-01-04 22:52:54.180689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1cae9f885da'
down_revision = 'f2a8a10034be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirement_groups',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('scope', sa.Enum('MAJOR', 'GEN_ED', name='requirement_scope'), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('rule_type', sa.Enum('ALL', 'ANY', 'CHOOSE_N', 'CREDITS_TOTAL', name='rule_type'), nullable=False),
    sa.Column('choose_n', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirement_slots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('requirement_group_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=250), nullable=False),
    sa.Column('min_credits_required', sa.Integer(), nullable=True),
    sa.Column('slot_type', sa.Enum('COURSE', 'BUCKET', 'BUNDLE', name='slot_type'), nullable=False),
    sa.Column('slot_rule', sa.JSON(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requirement_group_id'], ['requirement_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requirement_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirement_slots_requirement_group_id'), ['requirement_group_id'], unique=False)

    op.create_table('course_bundles',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('requirement_slot_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('note', sa.String(length=250), nullable=True),
    sa.Column('must_be_same_term', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requirement_slot_id'], ['requirement_slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requirement_slot_id', 'label', name='uq_bundle_label_per_slot')
    )
    with op.batch_alter_table('course_bundles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_bundles_requirement_slot_id'), ['requirement_slot_id'], unique=False)

    op.create_table('course_options',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('requirement_slot_id', sa.String(length=64), nullable=True),
    sa.Column('bundle_id', sa.String(length=64), nullable=True),
    sa.Column('course_id', sa.String(length=64), nullable=False),
    sa.Column('note', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(requirement_slot_id IS NOT NULL AND bundle_id IS NULL) OR (requirement_slot_id IS NULL AND bundle_id IS NOT NULL)', name='ck_course_option_parent_xor'),
    sa.ForeignKeyConstraint(['bundle_id'], ['course_bundles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['requirement_slot_id'], ['requirement_slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_options_bundle_id'), ['bundle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_options_requirement_slot_id'), ['requirement_slot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_options_requirement_slot_id'))
        batch_op.drop_index(batch_op.f('ix_course_options_bundle_id'))

    op.drop_table('course_options')
    with op.batch_alter_table('course_bundles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_bundles_requirement_slot_id'))

    op.drop_table('course_bundles')
    with op.batch_alter_table('requirement_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirement_slots_requirement_group_id'))

    op.drop_table('requirement_slots')
    op.drop_table('requirement_groups')
    # ### end Alembic commands ###
