"""Ontology + Catalog models final

Revision ID: f2a8a10034be
Revises: 95dd7869c924
Create Date: 2026-01-04 22:47:57.520526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2a8a10034be'
down_revision = '95dd7869c924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_offerings', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('campus_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_course_offerings_campus_id'), ['campus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_offerings_course_id'), ['course_id'], unique=False)
        batch_op.create_unique_constraint('uq_offering_course_campus', ['course_id', 'campus_id'])

    with op.batch_alter_table('majors', schema=None) as batch_op:
        batch_op.alter_column('degree',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Enum('BA', 'BS', 'BFA', 'BM', name='degree_enum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('majors', schema=None) as batch_op:
        batch_op.alter_column('degree',
               existing_type=sa.Enum('BA', 'BS', 'BFA', 'BM', name='degree_enum'),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('course_offerings', schema=None) as batch_op:
        batch_op.drop_constraint('uq_offering_course_campus', type_='unique')
        batch_op.drop_index(batch_op.f('ix_course_offerings_course_id'))
        batch_op.drop_index(batch_op.f('ix_course_offerings_campus_id'))
        batch_op.alter_column('campus_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('course_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###
